### ISSUE TITLE
Opencv 已经更新到4.9.0，求教大佬为什么使用您的build.sh 4.9.0 编译成功后没有wechat_qrcode相关代码

### ISSUE THREAD

**Issue by MrBugDou** [0x1306a94/WeChatQRCodeScanner#12]
盼回复呀大佬

**Comment by 0x1306a94** [comment]
我看了下 4.9.0 Apple平台代码使用 visionOS 标志，你用Xcode 15.2 编译试试，我这只有Xcode 15.0.1 也无法编译.
你拉取 opencv_4.9.0 这个分支，然后使用`./script/build.sh 4.9.0` @MrBugDou

**Comment by MrBugDou** [comment]
好的，谢谢，我更新Xcode试试

**Comment by 0x1306a94** [comment]
编译成功后没有wechat_qrcode相关代码，是因为脚本中的`--without objdetect`参数导致`wechat_qrcode`自动被禁用了。
opencv_contrib 4.9.0 版本中的 wechat_qrcode 依赖了 objdetect
我最开始的版本是依赖的 opencv_contrib c10b07de6d9fcc3222fd4d9ec865b99fd1798e2f 这个commit

拉下 opencv_4.9.0 分支，我这可以编译通过了 https://github.com/0x1306a94/WeChatQRCodeScanner/releases/tag/lib-v4.9.0

**Comment by MrBugDou** [comment]
大佬就是🐮啊😂，可以用了，不过我删除--without objdetect还是不对，4.9.0 Mat类获取坐标方式变了，我在研究研究，您是在哪看的资料呀，方便分享一下么，想学习一下，谢谢

**Comment by 0x1306a94** [comment]
https://github.com/opencv/opencv_contrib/blob/4.x/modules/wechat_qrcode/CMakeLists.txt#L2C60-L2C87 需要去掉这两个，但是去查看这两个自身的依赖项是不是在 脚本的 --without 列表中，在的也需要去掉 @MrBugDou

**Comment by MrBugDou** [comment]
好的，我试试，谢谢

**Comment by MrBugDou** [comment]
<img width="415" alt="image" src="https://github.com/0x1306a94/WeChatQRCodeScanner/assets/12947653/e85d933c-4417-404a-b4c3-1fde00861f08">
@0x1306a94 大佬您好
上面是我编译的头文件列表，下面是您编译的头文件列表，不知道为什么我编译的结果就是链接不到wechat，而且我发现您编译的是xcframework，我用build.sh编译的产物是framework，方便把您的编译脚本贴我看看么，对了我的cmake版本是3.28.1，和这个又关系么？

**Comment by 0x1306a94** [comment]
如果你用的新版本的 wechat_qrcode 代码编译，并且编译后没有wechat_qrcode对应的头文件，说明被自动禁用了，导致被自动禁用是因为依赖缺失，你可以试试把  --without 全去掉再编译看看
@MrBugDou

**Comment by MrBugDou** [comment]
@0x1306a94 感谢，刚才试了，确实是删除所有--without后就有微信了，就是编译产物太大了😂

**Comment by 0x1306a94** [comment]
> @0x1306a94 感谢，刚才试了，确实是删除所有--without后就有微信了，就是编译产物太大了😂

你可以自己看它依赖了那些，然后把不要的通过--without 去掉就好了

**Comment by MrBugDou** [comment]
删除   objdetect、calib3d、features2d、flann 后成功了，前两个我是看到有依赖，但是后面两个不知道在哪依赖了，找半天没找到😮‍💨

**Comment by 0x1306a94** [comment]
间接依赖的
比如 wechat_qrcode 依赖 objdetect 而 objdetect 自身又依赖 features2d

**Comment by MrBugDou** [comment]
哦，看到了，是objdetect 依赖 calib3d，然后calib3d依赖features2d、flann，开始没注意看calib3d的依赖
