### ISSUE TITLE
'opencv2/Mat.h' file not found

### ISSUE THREAD

**Issue by Wbqqqq** [0x1306a94/WeChatQRCodeScanner#2]
gitclone和pod install。我发现pod工程里没有把openvc的frameword引进来。是我的问题吗。。。

**Comment by Wbqqqq** [comment]
![image](https://user-images.githubusercontent.com/17332298/106689273-a9d5cf80-660a-11eb-9272-a9e140afb854.png)

**Comment by 0x1306a94** [comment]
@Wbqqqq 更新下最新的

**Comment by Wbqqqq** [comment]
可以了 想问老哥有在商用吗，我准备把我们这边的全部换掉了。

**Comment by 0x1306a94** [comment]
@Wbqqqq 我也是这周一才看到,然后就弄了下
