### ISSUE TITLE
将VALID_ARCHS改为arm64 x86_64 armv7 armv7s

### ISSUE THREAD

**Issue by Wbqqqq** [0x1306a94/WeChatQRCodeScanner#3]
大佬  lipo -info /Users/wbq/Desktop/liubikecustomer_ios/WeChatQRCodeScanner/Frameworks/opencv2.framework/opencv2 
Architectures in the fat file: /Users/wbq/Desktop/liubikecustomer_ios/WeChatQRCodeScanner/Frameworks/opencv2.framework/opencv2 are: x86_64 arm64

lipo还是只有两个架构。。

**Comment by 0x1306a94** [comment]
armv7 armv7s 可以去掉呀

**Comment by 0x1306a94** [comment]
@Wbqqqq armv7 armv7s 可以去掉了, 或者你参考脚本自己编译
[build.sh#L62](https://github.com/0x1306a94/WeChatQRCodeScanner/blob/master/script/build.sh#L62)
```shell
--iphoneos_archs arm64,armv7,armv7s
```

**Comment by Wbqqqq** [comment]
可以了，感谢。这个patch是官方提供的吗 T_T

**Comment by 0x1306a94** [comment]
@Wbqqqq 是我改的

**Comment by Wbqqqq** [comment]
膜拜大佬
