### ISSUE TITLE
怎样识别相册中图片的二维码信息？

### ISSUE THREAD

**Issue by gu2890961** [0x1306a94/WeChatQRCodeScanner#4]
你好，我们扫一扫一般有从相册中选择图片功能，能否加个识别图片二维码信息功能？

**Comment by 0x1306a94** [comment]
@gu2890961 由于大多数的APP 扫码都有自己的UI样式,所有此库主要是提供一个编译好,经过裁剪的静态库,关于相册识别,无非就是把相机输入改成图片输入就好了

**Comment by gu2890961** [comment]
我试着把UIImage转CVImageBufferRef，然后发现识别不到二维码，是不是我的方向有问题，由于对open cv不熟，大佬能不能贴部分代码，感谢！

**Comment by 0x1306a94** [comment]
@gu2890961 参考develop分支

**Comment by gu2890961** [comment]
不愧是大佬，膜拜，解决了我图片二维码识别不了的问题。微信识别二维码确实比其他自带或者Z_xing利害些，有张图片他们识别不了，这个微信的可以识别出来
